version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "4000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
    # We can define environmental variables in this way too
    # environment:
    #   - DATABASE_HOSTNAME=localhost

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: